name: Release Hydra

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
  
  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - create-release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hydra-devops
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
  
  create-release:
    name: create release 
    needs:
    - build #for testing, change back to push-to-testpypi 
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Download dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        version="v$(cat hydra/__init__.py | sed 's/VERSION = //' | sed 's/\"//g')"
        test="test"
        echo "::debug:: $version"
        echo "::debug:: $test"
        echo "::debug:: debugging"
        #gh release create "$version"
        #--title "$version" 
        #--repo '${{ github.repository }}' 
        #--notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        "v$(cat hydra/__init__.py | sed 's/VERSION=//')" dist/**
        --repo '{{ github.repository }}'

  publish-to-testpypi:
      name: Publish to TestPyPI
      needs:
      - build
      runs-on: ubuntu-latest
      environment:
        name: testpypi
        url: https://test.pypi.org/p/hydra-devops
      permissions:
        id-token: write
      steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
