name: Test Hydra

on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  unit:
    runs-on: ubuntu-latest
    name: unit tests
    if: github.even_name == 'push'
    strategy:
      matrix:
        version: ["3.11", "3.12", "3.13"]
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.version}}
      - name: checkout
        uses: actions/checkout@v2
      - name: run tox
        id: tox
        #TODO: switch to commit sha
        uses: paolorechia/pox@v1.0
        with:
          tox_env: "py{{matrix.version}}-unit"
      - name: check for success
        run: |
          echo "Units tests have passed: ${{steps.tox.outputs.success_flag}}"
  system:
    runs-on: ubuntu-latest
    name: system tests
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        version: ["3.11", "3.12", "3.13"]
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.version}}
      - name: checkout
        uses: actions/checkout@v2
      - name: run tox
        id: tox
        #TODO: switch to commit sha
        uses: paolorechia/pox@v1.0
        with:
          tox_env: "py{{matrix.version}}-system"
      - name: check for success
        run: |
          echo "System tests have passed: ${{steps.tox.outputs.success_flag}}"
